Add Component on Feature-components Branch
Anvi98/math-magicians pull request #2
Opened 2021-08-10 22:01 UTC by Anvi98

- Delete all the boilerplate from CRA (text, images, styles).
- Create a directory called `components`.
- Inside `components`, create a new `Calculator.js` file.
- In `Calculator.js`, create a React component that matches the design.

- Don't add any extra design.
- Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
- Use class-based components.
- Once the Calculator is ready, import it and use it in your main component (App.js).
- Test it in the browser; it should render without problems.

2021-08-10 22:23 UTC, DeliceLydia requested changes
# Hi @Anvi98👏👏, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 22:23 UTC, DeliceLydia commented on src/App.js
> +      <Calculator />
- [ ] The `App.js` component should be class-based please work on that

2021-08-10 22:23 UTC, DeliceLydia commented on src/index.js
>  import reportWebVitals from './reportWebVitals.js';
- [ ] Please remove all the boilerplate that was created that you will not use in your app like(
texts, images, and styles)

2021-08-10 22:23 UTC, DeliceLydia commented on src/components/Calculator.css
> +}
- [ ] Try to follow the given design

Design
![design](https://user-images.githubusercontent.com/44745855/128942463-b88e9eda-143e-4574-ac94-ce2a6b4ee6dd.png)

yours
![yr](https://user-images.githubusercontent.com/44745855/128942485-e49285a3-50c3-4b15-93c7-daa231d9f014.png)

2021-08-10 22:33 UTC, Anvi98 commented
Except for the picture, all your reviews are from the dev branch and not the current-branch feature components.
Could you please check the current branch?

2021-08-11 00:16 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-08-11 00:23 UTC, merged